version: "3.9"
services:
  backstop:
    container_name: backstop-js
    build: backstop/.
    volumes:
      - backstop:/src/backstop_data
      - ./backstop:/src
    entrypoint: "backstop"
#    stdin_open: true # docker run -i
#    tty: true        # docker run -t
    command:
      - "test"
  nginx:
    container_name: backstop-nginx
    build: nginx/.
    depends_on:
      - backstop
    volumes:
      - backstop:/src/
    ports:
      - "80:80"
volumes:
  backstop:
    external: true