version: "3.9"
services:
  backstop:
    build: backstop/.
    volumes:
      - backstop:/src
    command:
      - "test"
  nginx:
    build: nginx/.
    #https://www.nginx.com/resources/wiki/start/topics/examples/full/
    depends_on:
      - backstop
    volumes:
      - backstop:/src
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
volumes:
  backstop:
