
version: "3.9"
services:
  backstop:
    container_name: pixel-sentry
    build: ./
    stdin_open: true
    volumes:
      - ./config:/src/config
  nginx:
    container_name: pixel-nginx
    build: nginx/.
    volumes:
      - ./config/html:/usr/share/nginx/html
    ports:
      - "8080:80"