version: "3.9"
services:
  backstop:
    container_name: backstop-js
    build: backstop/.
    volumes:
      - backstop:/src
    command:
      - "test"
  nginx:
    container_name: backstop-nginx
    build: nginx/.
    #https://www.nginx.com/resources/wiki/start/topics/examples/full/
    depends_on:
      - backstop
    volumes:
      - backstop:/src
      - ./volume:/src/backstop_data
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
volumes:
  backstop:
    external: true