version: "3.9"
services:
  backstop:
    build: backstop/.
    image: glad2os/backstop:latest
    volumes:
      - backstop:/usr/src/app
  nginx:
    build: nginx/.
    #https://www.nginx.com/resources/wiki/start/topics/examples/full/
    depends_on:
      - backstop
    volumes:
      - backstop:/usr/src/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
volumes:
  backstop:
