---
  - name: Backstop JS first deployment playbook
    hosts: aws
    become: yes
    become_user: "{{ansible_user}}"
    tasks:
      - name: Stop current docker-compose
        community.docker.docker_compose:
          project_src: "{{hostname.project_path}}"
          build: false
          stopped: true
        ignore_errors: yes

      - name: Update a repository
        ansible.builtin.shell: git pull
        args:
          chdir: "{{hostname.project_path}}"

      - name: Run docker-compose up
        community.docker.docker_compose:
          project_src: "{{hostname.project_path}}"
          build: true