---
  - name: Backstop JS first deployment playbook
    hosts: aws
    become: yes
    become_user: "{{ansible_user}}"
    tasks:
      - name: Stop current docker-compose
        community.docker.docker_compose:
          project_src: "{{hostname.project_path}}"
          build: false
          stopped: true

      - name: Git pull a new version
        ansible.builtin.git:
          repo: https://github.com/glad2os/backstop-docker-nginx.git
          dest: "{{hostname.project_path}}"
          refspec: '+refs/pull/*:refs/heads/*'

      - name: Run docker-compose up
        community.docker.docker_compose:
          project_src: "{{hostname.project_path}}"
          build: true